
/* Drop Tables */

DROP TABLE R9_MEMBER CASCADE CONSTRAINTS;
DROP TABLE R9_ROOM_TEMP CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE R9_MEMBER
(
	MNO number NOT NULL,
	EMAILID varchar2(100) NOT NULL UNIQUE,
	PWD varchar2(20) NOT NULL,
	NAME nvarchar2(20) NOT NULL,
	PHONENUMBER nvarchar2(20) NOT NULL,
	KAKAOID number,
	PRIMARY KEY (MNO)
);


CREATE TABLE R9_ROOM_TEMP
(
	NO number NOT NULL,
	RNAME nvarchar2(100) NOT NULL,
	RADDR nvarchar2(100) NOT NULL,
	PAYPHOUR number NOT NULL,
	CATEGORY nvarchar2(50) NOT NULL,
	PEOPLECOUNT number NOT NULL,
	PRIMARY KEY (NO)
);


/* Create SEQUENCES */
CREATE SEQUENCE SEQ_R9_MEMBER NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_R9_ROOM_TEMP NOCACHE NOCYCLE;
