
/* Drop Tables */

DROP TABLE CRAWLING_TABLE CASCADE CONSTRAINTS;
DROP TABLE R9_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE R9_ROOM CASCADE CONSTRAINTS;
DROP TABLE R9_HOST CASCADE CONSTRAINTS;
DROP TABLE R_BOARD CASCADE CONSTRAINTS;
DROP TABLE R_NOTICE CASCADE CONSTRAINTS;
DROP TABLE R_SUGGESTION CASCADE CONSTRAINTS;
DROP TABLE R9_MEMBER CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_R9_HOST;
DROP SEQUENCE SEQ_R9_MEMBER
DROP SEQUENCE SEQ_R9_MEMBER;
DROP SEQUENCE SEQ_R9_REGIST;
DROP SEQUENCE SEQ_R9_RESERVATION;
DROP SEQUENCE SEQ_R9_ROOM;
DROP SEQUENCE SEQ_R_BOARD;
DROP SEQUENCE SEQ_R_NOTICE;
DROP SEQUENCE SEQ_R_SUGGESTION;




/* Create Sequences */

CREATE SEQUENCE SEQ_R9_HOST INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_MEMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_MEMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_REGIST INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_RESERVATION INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_ROOM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R_BOARD INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R_NOTICE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R_SUGGESTION INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE CRAWLING_TABLE
(
	CNO number NOT NULL,
	TITLE nvarchar2(100),
	LINKURL nvarchar2(500),
	AREA nvarchar2(100),
	TAGS nvarchar2(100),
	PRICE nvarchar2(50),
	IMG nvarchar2(200),
	PRIMARY KEY (CNO)
);


CREATE TABLE R9_HOST
(
	H_NO number NOT NULL,
	M_NO number NOT NULL,
	H_NAME varchar2(20) NOT NULL,
	H_EMAIL varchar2(100) NOT NULL,
	H_TEL varchar2(20) NOT NULL,
	H_COMPANY varchar2(20) NOT NULL,
	H_ADDRESS varchar2(500) NOT NULL,
	H_COMPANY_TEL varchar2(20) NOT NULL,
	H_FAX varchar2(20),
	H_OWNER varchar2(20) NOT NULL,
	H_REGISTRATION varchar2(200) NOT NULL,
	H_BUSINESS varchar2(500),
	H_STOKE varchar2(500),
	H_MANAGER varchar2(20) NOT NULL,
	H_MANAGER_MAIL varchar2(100) NOT NULL,
	H_MANAGER_TEL varchar2(20) NOT NULL,
	H_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (H_NO)
);


CREATE TABLE R9_MEMBER
(
	M_NO number NOT NULL,
	M_EMAIL varchar2(100) UNIQUE,
	KAKAO varchar2(20),
	NAVER varchar2(20),
	GOOGLE varchar2(20),
	FACEBOOK varchar2(20),
	M_PWD varchar2(20) NOT NULL,
	M_NAME varchar2(20) NOT NULL,
	M_TEL varchar2(20) NOT NULL,
	M_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (M_NO)
);


CREATE TABLE R9_RESERVATION
(
	S_NO number NOT NULL,
	M_NO number NOT NULL,
	R_NO number NOT NULL,
	S_MONEY number,
	S_RESERVATION_DATE varchar2(50),
	S_NAME varchar2(10),
	S_TEL varchar2(20),
	S_MAIL varchar2(100),
	S_PEOPLE_COUNT number,
	S_PLUS_PEOPLE number,
	S_NOTICE varchar2(4000),
	S_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (S_NO)
);


CREATE TABLE R9_ROOM
(
	R_NO number NOT NULL,
	H_NO number NOT NULL,
	R_NAME varchar2(50),
	R_ADDRESS varchar2(500),
	R_IMAGE_1 clob,
	R_IMAGE_2 clob,
	R_IMAGE_3 clob,
	R_IMAGE_4 clob,
	R_IMAGE_5 clob,
	R_CATEGORY varchar2(3000),
	R_TIME varchar2(2000),
	R_DAY varchar2(1000),
	R_GUID varchar2(4000),
	R_MONEY nvarchar2(2000),
	R_SMALL_CONTENT varchar2(1000),
	R_LARGE_CONTENT varchar2(4000),
	R_TAG_1 varchar2(200),
	R_TAG_2 varchar2(200),
	R_TAG_3 varchar2(200),
	R_WARNING varchar2(4000),
	R_EMAIL_TEL varchar2(1000),
	R_REFUND varchar2(4000),
	R_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (R_NO)
);


CREATE TABLE R_BOARD
(
	B_NO number NOT NULL,
	M_NO number NOT NULL,
	B_TITLE varchar2(300),
	B_CONTENT varchar2(4000),
	B_POSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (B_NO)
);


CREATE TABLE R_NOTICE
(
	N_NO number NOT NULL,
	M_NO number NOT NULL,
	N_TITLE varchar2(500),
	N_CONTENT varchar2(4000),
	N_POSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (N_NO)
);


CREATE TABLE R_SUGGESTION
(
	G_NO number NOT NULL,
	M_NO number NOT NULL,
	G_TITLE varchar2(300),
	G_CONTENT varchar2(4000),
	G_POSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (G_NO)
);



/* Create Foreign Keys */

ALTER TABLE R9_ROOM
	ADD FOREIGN KEY (H_NO)
	REFERENCES R9_HOST (H_NO)
;


ALTER TABLE R9_HOST
	ADD FOREIGN KEY (M_NO)
	REFERENCES R9_MEMBER (M_NO)
;


ALTER TABLE R9_RESERVATION
	ADD FOREIGN KEY (M_NO)
	REFERENCES R9_MEMBER (M_NO)
;


ALTER TABLE R_BOARD
	ADD FOREIGN KEY (M_NO)
	REFERENCES R9_MEMBER (M_NO)
;


ALTER TABLE R_NOTICE
	ADD FOREIGN KEY (M_NO)
	REFERENCES R9_MEMBER (M_NO)
;


ALTER TABLE R_SUGGESTION
	ADD FOREIGN KEY (M_NO)
	REFERENCES R9_MEMBER (M_NO)
;


ALTER TABLE R9_RESERVATION
	ADD FOREIGN KEY (R_NO)
	REFERENCES R9_ROOM (R_NO)
;



