
/* Drop Tables */

DROP TABLE R9_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE R9_ROOM CASCADE CONSTRAINTS;
DROP TABLE R9_HOST CASCADE CONSTRAINTS;
DROP TABLE R9_MEMBER CASCADE CONSTRAINTS;


/* Drop Sequences */

DROP SEQUENCE SEQ_R9_HOST;
DROP SEQUENCE SEQ_R9_MEMBER;
DROP SEQUENCE SEQ_R9_REGIST;
DROP SEQUENCE SEQ_R9_RESERVATION;
DROP SEQUENCE SEQ_R9_ROOM;



/* Create Sequences */

CREATE SEQUENCE SEQ_R9_HOST INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_MEMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_REGIST INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_RESERVATION INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_R9_ROOM INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE R9_HOST
(
	H_NO number NOT NULL,
	M_NO number NOT NULL,
	H_NAME varchar2(20) NOT NULL,
	H_EMAIL varchar2(100) NOT NULL,
	H_TEL varchar2(20) NOT NULL,
	H_COMPANY varchar2(20) NOT NULL,
	H_ADDRESS varchar2(500) NOT NULL,
	H_COMPANY_TEL varchar2(20) NOT NULL,
	H_FAX varchar2(20),
	H_OWNER varchar2(20) NOT NULL,
	H_REGISTRATION varchar2(20) NOT NULL,
	H_BUSINESS varchar2(50),
	H_STOKE varchar2(50),
	H_REGISTRATION_FILE varchar2(260) NOT NULL,
	H_ACCOUNT_FILE varchar2(260) NOT NULL,
	H_MANAGER varchar2(20) NOT NULL,
	H_MANAGER_MAIL varchar2(100) NOT NULL,
	H_MANAGER_TEL varchar2(20) NOT NULL,
	H_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (H_NO)
);


CREATE TABLE R9_MEMBER
(
	M_NO number NOT NULL,
	M_EMAIL varchar2(100) UNIQUE,
	KAKAO varchar2(20),
	NAVER varchar2(20),
	GOOGLE varchar2(20),
	FACEBOOK varchar2(20),
	M_PWD varchar2(20) NOT NULL,
	M_NAME varchar2(20) NOT NULL,
	M_TEL varchar2(20) NOT NULL,
	M_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (M_NO)
);


CREATE TABLE R9_RESERVATION
(
	S_NO number NOT NULL,
	M_NO number NOT NULL,
	R_NO number NOT NULL,
	S_MONEY number,
	S_RESERVATION_DATE varchar2(50),
	S_NAME varchar2(10),
	S_TEL varchar2(20),
	S_MAIL varchar2(100),
	S_PEOPLE_COUNT number,
	S_PLUS_PEOPLE number,
	S_NOTICE varchar2(4000),
	S_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (S_NO)
);


CREATE TABLE R9_ROOM
(
	R_NO number NOT NULL,
	H_NO number NOT NULL,
	R_NAME varchar2(50),
	R_CATEGORY varchar2(50),
	R_PEOPLE_COUNT_MIN varchar2(20),
	R_PEOPLE_COUNT_MAX varchar2(20),
	R_MONEY number,
	R_SMALL_CONTENT varchar2(1000),
	R_LARGE_CONTENT varchar2(4000),
	R_TAG_1 varchar2(20),
	R_TAG_2 varchar2(20),
	R_TAG_3 varchar2(20),
	R_GUID varchar2(4000),
	R_WARNING varchar2(4000),
	R_TIME varchar2(20),
	R_HOLIDAY varchar2(100),
	R_IMAGE_1 varchar2(260),
	R_IMAGE_2 varchar2(260),
	R_IMAGE_3 varchar2(260),
	R_IMAGE_4 varchar2(260),
	R_IMAGE_5 varchar2(260),
	R_EMAIL varchar2(100),
	R_TEL varchar2(20),
	R_ADDRESS varchar2(500),
	R_ACCOUNT_BANK varchar2(20),
	R_ACCOUNT_NUMBER varchar2(30),
	R_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (R_NO)
);



/* Create Foreign Keys */

ALTER TABLE R9_ROOM
	ADD FOREIGN KEY (H_NO)
	REFERENCES R9_HOST (H_NO)
;


ALTER TABLE R9_HOST
	ADD FOREIGN KEY (M_NO)
	REFERENCES R9_MEMBER (M_NO)
;


ALTER TABLE R9_RESERVATION
	ADD FOREIGN KEY (M_NO)
	REFERENCES R9_MEMBER (M_NO)
;


ALTER TABLE R9_RESERVATION
	ADD FOREIGN KEY (R_NO)
	REFERENCES R9_ROOM (R_NO)
;



